### PR TITLE
Fixed MemoryError

### PR DESCRIPTION
**Pull request by litefeel**

### CODE REVIEW

**Comment by litefeel** [comment]
I do n’t know why https://github.com/faelenor/asset-bundle-analyzer/issues/4 also disappeared

**Comment by faelenor** [comment]
Thank you for the pull request. Could you please explain each change and provide a concrete example of the issues they are fixing?

**Comment by litefeel** [comment]
When binary2text exports a large asset bundle,
The output text file is also very large.
For example 500M.
When Python reads everything into memory at once, it will raise a `MemoryError`.

**Comment by ethiffeault** [comment]
I had the same problem, are you using python 32 bit ? using 64 bit fixed it

**Comment by faelenor** [comment]
If you can provide a reproducible scenario with Python 64 bit, I'll consider this but I never had this issue.

**Pull request closed without merging**
